provider:
  name: faas
  gateway: http://192.168.1.113:8080

functions:
  echo:
    lang: go
    handler: ./echo
    image: nicholasjackson/func_echo
  s3upload:
    lang: go
    handler: ./s3upload
    image: nicholasjackson/func_s3upload
    environment:
      bucket: "mybucket.name"
      accessKeyID: "xxxxxxxxxxxx"
      secretAccessKey: "xxxxxxxxxx"
      region: "eu-west-1"
